/**
 * ==============================================================================
 * PDF EXTRACTION UTILITY (PDF.js ENGINE)
 * ==============================================================================
 * @fileoverview robust PDF text extraction module designed for Node.js.
 * It utilizes the legacy build of PDF.js to parse complex documents (including
 * those generated by tools like Canva) without requiring OCR.
 *
 * @author Sacha Pastor
 * @environment Node.js (ES Modules)
 * @dependencies pdfjs-dist
 * ==============================================================================
 */

// --- 1. CORE IMPORTS ---
import fs from 'node:fs';
// import path from 'node:path'; // Unused in this snippet, kept if needed for future expansion.

// --- 2. LIBRARY INITIALIZATION ---

// Dynamically import the legacy build of PDF.js compatible with Node.js environments.
// NOTE: Top-level await is used here to ensure the library is loaded before execution.
// The 'legacy' build is required to avoid standard DOM dependency issues in Node.
const pdfjsLib = await import('pdfjs-dist/legacy/build/pdf.mjs');

// --- 3. CONFIGURATION CONSTANTS ---

// Maximum number of pages to scan to avoid memory overload on massive documents.
const MAX_PAGES_TO_SCAN = 10;

// Minimum character count to consider extraction successful.
const MIN_TEXT_THRESHOLD = 50;

/**
 * Extracts text content from a PDF file page by page.
 *
 * @param {string} absolutePath - The absolute file system path to the PDF.
 * @returns {Promise<string>} The extracted text content joined by newlines.
 * @throws {Error} If the file does not exist.
 */
export async function extractPdfText(absolutePath) {
    // 1. Validation: Ensure the file exists before attempting processing
    if (!fs.existsSync(absolutePath)) {
        throw new Error(`File not found at path: ${absolutePath}`);
    }

    try {
        // 2. Data Preparation: Read file into a Uint8Array buffer
        // PDF.js requires a TypedArray (Uint8Array) rather than a standard Node Buffer.
        const buffer = fs.readFileSync(absolutePath);
        const uint8Array = new Uint8Array(buffer);

        // 3. Document Loading & Configuration
        // CRITICAL CONFIGURATION:
        // - disableWorker: true -> Forces execution on the main thread.
        //   This is necessary in Node.js to avoid "Invalid workerSrc type" errors.
        // - isEvalSupported: false -> Security measure to disable code evaluation.
        const loadingTask = pdfjsLib.getDocument({
            data: uint8Array,
            disableWorker: true,
            isEvalSupported: false
        });

        const pdfDocument = await loadingTask.promise;

        let fullText = "";
        
        // Determine the loop limit (actual pages vs safety limit)
        const pagesToProcess = Math.min(pdfDocument.numPages, MAX_PAGES_TO_SCAN);

        // 4. Page Iteration and Extraction
        for (let i = 1; i <= pagesToProcess; i++) {
            // Get page reference
            const page = await pdfDocument.getPage(i);
            
            // Extract text content items
            const textContent = await page.getTextContent();

            // Reconstruct text from the content items.
            // Items are often fragmented; joining with a space preserves basic readability.
            const pageText = textContent.items
                .map(item => item.str)
                .join(' ');

            // Append to full text if content exists
            if (pageText.trim().length > 0) {
                fullText += `\n--- PAGE ${i} ---\n\n${pageText}`;
            }
        }

        // 5. Result Verification
        // Check if the extracted text meets the minimum threshold.
        // If not, the PDF might be an image-only scan or encrypted.
        if (!fullText || fullText.trim().length < MIN_TEXT_THRESHOLD) {
            console.warn(`[PDF WARN] Extracted text is empty or insufficient (${fullText.length} chars).`);
            return "[SYSTEM] The document appears to be empty, image-based, or protected. Native extraction failed.";
        }

        return fullText;

    } catch (error) {
        // Log the critical error for debugging purposes
        console.error("[PDF ERROR] Critical failure in pdfjs-dist:", error);
        return "[ERROR] Unable to read the PDF file due to an internal error.";
    }
}